import type { HousingListing, Transport, WorkLocation } from './types'

export const transportOptions: Array<{ value: Transport; label: string }> = [
  { value: '地铁', label: '地铁' },
  { value: '公交', label: '公交' },
  { value: '驾车', label: '驾车' },
  { value: '骑行', label: '骑行' },
  { value: '步行', label: '步行' },
]

export const demoOffice: WorkLocation = {
  id: 'hongqiao',
  name: '上海虹桥商务区',
  subtitle: '长宁区 · 闵行区交界',
  coords: [31.1979, 121.3211],
}

const makeCommute = (
  mode: Transport,
  time: number,
  transfers: number,
  walk: number,
  cost: number,
  reliability: number,
  summary: string,
) => ({ mode, time, transfers, walk, cost, reliability, summary })

export const demoListings: HousingListing[] = [
  {
    id: 'hongqiao-yunji',
    title: '虹桥云际一居',
    district: '闵行 · 龙柏新村',
    address: '金汇路 88 弄 · 近龙溪路站',
    coords: [31.1765, 121.361],
    rent: 4200,
    bedrooms: '一室一厅',
    area: 43,
    image: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1000&q=85',
    station: '龙溪路站',
    stationDistance: '步行 6 分钟',
    buildYear: 2016,
    highlights: ['朝南采光', '独立厨房', '物业安静'],
    tags: ['少换乘', '可短租', '采光好'],
    description: '适合希望住得安静、每天通勤路线简单的上班族。小区生活配套完整，晚归也方便。',
    commute: {
      地铁: makeCommute('地铁', 28, 0, 8, 4, 91, '10 号线直达'),
      公交: makeCommute('公交', 34, 0, 10, 2, 79, '公交 57 路直达'),
      驾车: makeCommute('驾车', 18, 0, 3, 9, 66, '高峰期较拥堵'),
      骑行: makeCommute('骑行', 25, 0, 2, 0, 73, '沿虹桥路骑行'),
      步行: makeCommute('步行', 67, 0, 0, 0, 88, '一路少红绿灯'),
    },
  },
  {
    id: 'gubei-qingju',
    title: '古北轻居公寓',
    district: '长宁 · 古北',
    address: '黄金城道 218 号 · 近伊犁路站',
    coords: [31.192, 121.397],
    rent: 4900,
    bedrooms: '一室一厅',
    area: 39,
    image: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1000&q=85',
    station: '伊犁路站',
    stationDistance: '步行 4 分钟',
    buildYear: 2020,
    highlights: ['精装拎包住', '楼下商业丰富', '门禁严格'],
    tags: ['生活方便', '精装修', '安全感高'],
    description: '周边餐饮、便利店和健身房密集，适合下班后不想长距离移动的生活方式。',
    commute: {
      地铁: makeCommute('地铁', 31, 1, 7, 4, 93, '10 号线 → 2 号线'),
      公交: makeCommute('公交', 42, 0, 8, 2, 76, '公交换乘少'),
      驾车: makeCommute('驾车', 25, 0, 3, 11, 61, '高峰期路口多'),
      骑行: makeCommute('骑行', 24, 0, 2, 0, 81, '城市道路平整'),
      步行: makeCommute('步行', 74, 0, 0, 0, 88, '适合周末散步'),
    },
  },
  {
    id: 'hanghua-living',
    title: '航华生活里',
    district: '闵行 · 航华',
    address: '航新路 399 弄 · 近航中路站',
    coords: [31.159, 121.327],
    rent: 3500,
    bedrooms: '两室一厅合租',
    area: 26,
    image: 'https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=1000&q=85',
    station: '航中路站',
    stationDistance: '步行 9 分钟',
    buildYear: 2013,
    highlights: ['预算友好', '采买方便', '室友作息稳定'],
    tags: ['性价比', '预算友好', '0 换乘'],
    description: '预算更友好的合租方案，适合刚入职、希望把租金压力控制在合理范围的用户。',
    commute: {
      地铁: makeCommute('地铁', 35, 0, 12, 4, 87, '10 号线直达'),
      公交: makeCommute('公交', 40, 0, 9, 2, 74, '公交 776 路'),
      驾车: makeCommute('驾车', 21, 0, 4, 8, 64, '停车较容易'),
      骑行: makeCommute('骑行', 22, 0, 1, 0, 77, '社区道路友好'),
      步行: makeCommute('步行', 59, 0, 0, 0, 87, '沿小区绿道'),
    },
  },
  {
    id: 'zhongshan-park',
    title: '中山公园松间',
    district: '长宁 · 中山公园',
    address: '愚园路 1288 号 · 近中山公园站',
    coords: [31.221, 121.405],
    rent: 5300,
    bedrooms: '一室一厅',
    area: 45,
    image: 'https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=1000&q=85',
    station: '中山公园站',
    stationDistance: '步行 5 分钟',
    buildYear: 2018,
    highlights: ['商圈成熟', '收纳充足', '采光通透'],
    tags: ['通勤快', '生活丰富', '大开间'],
    description: '用更高一点的预算换取成熟商圈和更快的通勤，适合想把生活半径缩小的人。',
    commute: {
      地铁: makeCommute('地铁', 24, 1, 6, 4, 94, '2 号线 → 10 号线'),
      公交: makeCommute('公交', 35, 0, 8, 2, 80, '公交直达核心区'),
      驾车: makeCommute('驾车', 23, 0, 4, 12, 58, '停车成本较高'),
      骑行: makeCommute('骑行', 29, 0, 2, 0, 79, '沿延安西路'),
      步行: makeCommute('步行', 76, 0, 0, 0, 86, '距离较远'),
    },
  },
  {
    id: 'qibao-riverside',
    title: '七宝河畔一室',
    district: '闵行 · 七宝',
    address: '漕宝路 1555 弄 · 近七宝站',
    coords: [31.153, 121.342],
    rent: 3800,
    bedrooms: '一室一厅',
    area: 41,
    image: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1000&q=85',
    station: '七宝站',
    stationDistance: '步行 8 分钟',
    buildYear: 2015,
    highlights: ['临近商场', '有阳台', '小区绿化好'],
    tags: ['生活感', '有阳台', '租金适中'],
    description: '通勤多几分钟，但能换来更大的居住空间和完整的社区生活。',
    commute: {
      地铁: makeCommute('地铁', 39, 0, 10, 4, 85, '9 号线 → 10 号线'),
      公交: makeCommute('公交', 48, 1, 8, 2, 69, '公交换乘一次'),
      驾车: makeCommute('驾车', 20, 0, 3, 8, 62, '高峰期波动明显'),
      骑行: makeCommute('骑行', 23, 0, 2, 0, 76, '河畔骑行路线'),
      步行: makeCommute('步行', 62, 0, 0, 0, 84, '适合周末'),
    },
  },
]
